
# Définir Alt+u pour activer le mode de copie
bind-key -n M-w copy-mode
bind-key -n M-h split-window -v -c "#{pane_current_path}" # Pane horizontal Alt+h
bind-key -n M-v split-window -h -c "#{pane_current_path}" # Pane horizontal Alt+h 

set -g mouse on
set -g base-index 1
set -g pane-base-index 1 
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "catppuccin/tmux"


run '~/.tmux/plugins/tpm/tpm'
